version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - 8080:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./www/html:/var/www/html
        depends_on:
            - php
    
    php:
        build: ./php
        volumes:
            - ./www/html:/var/www/html
        depends_on:
            - db
    
    db:
        image:  postgres:13-alpine
        ports:
            - 5432:5432
        volumes:
            - ./pgsql/data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            TZ: Asia/Tokyo
    
    pgadmin:
        image: dpage/pgadmin4:4.2
        container_name: pgadmin
        ports: 
            - 5050:80
        environment:
            PGADMIN_DEFAULT_EMAIL: root
            PGADMIN_DEFAULT_PASSWORD: root
            TZ: Asia/Tokyo
        hostname: pgadmin
        depends_on:
          - db
        restart: always
        
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 8888:80
        depends_on:
            - db